[tool.poetry]
name = "classespy"
version = "0.1"
description = "Classes and Testing phases on them in Python"
authors = ["heWolf"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
